files:
  - source: /res/values/strings.xml
    translation: /res/values-%two_letters_code%/strings.xml
  - source: /fastlane/metadata/android/en-US/*_description.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
